### ISSUE TITLE
時間控制不准

### ISSUE THREAD

**Issue by leielyq** [chloro-pn/event_pool#1]

**Comment by chloro-pn** [comment]
可以提供下详细的信息么，例如执行/测试代码，结果与预期哪里不符。

**Comment by leielyq** [comment]
同一个pool添加多个event  就会不准。

**Comment by leielyq** [comment]
请问cleanTimerEvent 怎么用，可以不传参数吗

**Comment by chloro-pn** [comment]
你说的不准是时间精度不准么，构造TimeEvent的时候用millisceonds试试，参考我最新的提交。cleanTimerEvent这个函数不是当前默认分支的函数吧，master分支废弃了

**Comment by leielyq** [comment]
> 同一个pool添加多个event 就会不准。

如果其中一个或多个event 超时，本来周期是1ms，但是实际花费了100ms，会导致这个pool里面的其他event也会超时吗？

因为我现在用的是一个pool只对应了一个event才比较准确

也可能是我clone的版本不对，有空重新调整一下

**Comment by chloro-pn** [comment]
实际花费了100ms，指的是event触发后的回调函数消耗100ms么，如果是的话：
会的，event都是在后台线程依次调用的，如果其中一个阻塞其他的都会等待。我自己用的时候默认的event都是轻量级操作（消耗时间忽略不计），这个情况之前没考虑到，后续可以加上executor特性，event触发的时候调度到executor上执行。
另外：如果操作系统不是实时操作系统的话，由于调度延迟会导致精度问题（可能会在你设置的time point后才触发）。这可能会导致数毫秒-数十毫秒的误差，所以不建议周期设置的太小。

**Comment by leielyq** [comment]
嗯啊，不是实时操作系统，windows测试的情况 没有阻塞的话 5ms 很稳定。
这个库还是解决了很多麻烦的，感谢。
